<a href="https://colab.research.google.com/github/ABHAYB642/Random-Forest-Regression/blob/main/Random_Forest_Regression_of_Generated_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

 **ABHAY BIRAMANE**
# RANDOM FOREST REGRESSION OF GENERATED DATA

### IMPORT LIBRARY

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

### Generate Dataset

In [ ]:
from sklearn.datasets import make_regression

In [ ]:
#without coefficient of underline model
x,y=make_regression(n_samples=500,n_features=5,coef=False,bias=12,noise=10,random_state=2529)

In [ ]:
#with coefficient of underline model
x,y,w=make_regression(n_samples=500,n_features=5,coef=True,bias=12,noise=10,random_state=2529)

In [ ]:
x.shape,y.shape

((500, 5), (500,))

In [ ]:
w #with coefficient of x

array([29.45661718, 60.14529878, 61.7409438 , 13.32437893, 99.08122896])

In [ ]:
x.shape,y.shape

((500, 5), (500,))

### Get First Five Rows of Target Variable y and Feature X

In [ ]:
x[0:5]

array([[ 0.77913208, -1.09701784, -0.14239962,  1.02427891, -1.0708024 ],
       [-0.6925009 ,  0.45535977,  0.34707569, -0.32456746,  0.21970203],
       [-0.03901601, -0.3265115 ,  0.59793721,  0.61686653, -0.6237489 ],
       [-0.61566117, -0.11782129, -0.98234619, -0.78292727,  0.42713048],
       [ 1.30822207, -0.72541559,  0.60187975,  0.33285998,  1.48506184]])

In [ ]:
y[0:5]

array([-136.21858395,   49.83118244,  -29.81097858,  -31.74001475,
        193.0687778 ])

### Get Shape of Dataframe

In [ ]:
x.shape,y.shape

((500, 5), (500,))

### Get Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=2529)
x_train.shape,x_test.shape,y_train.shape,y_test.shape

((350, 5), (150, 5), (350,), (150,))

### Get Regression Model Train

In [ ]:
from sklearn.ensemble import RandomForestRegressor
model=RandomForestRegressor()

In [ ]:
model.fit(x_train,y_train)

RandomForestRegressor()

### Get Model Prediction

In [ ]:
y_pred=model.predict(x_test)

In [ ]:
y_pred.shape

(150,)

In [ ]:
y_pred

array([ -22.41761417, -122.00589023,  -68.4760645 ,   62.65457558,
       -223.9692037 ,  200.15400295,   56.07125653, -165.89671468,
       -138.59120158,  -83.74877871,   85.47366197, -108.40995916,
         80.87162124,   10.37423989, -243.62808208,  -75.12193968,
         47.14633507,    1.78902582,   35.92403084,   57.73546214,
        -46.24543302,  156.92107047,  148.71278495,   56.06828191,
        149.99822817, -188.95149833,   -7.3292835 ,  -47.64916357,
        -57.76682924,    9.25089476,  -74.26638925,   39.67899009,
        179.66386749,  -53.67179669,   21.57437133,  162.6567828 ,
         17.24415917,  113.88484826,   18.87001082,    7.36956566,
         97.84061914,   35.86559311,  -38.62670736,  -18.70263598,
         -9.24192281,   59.55347334,  -19.64593289, -212.83930779,
       -150.32851656,    1.12294708,  -29.76387517,  -83.86223821,
         63.12755335,   73.79696417,  -68.12419368,  182.98398414,
        -26.06661111,  -12.89327994,   21.13962002,   16.50625

### Get Model Evaluation

In [ ]:
from sklearn.metrics import mean_squared_error,mean_absolute_error, mean_absolute_percentage_error, r2_score

In [ ]:
mean_squared_error(y_test,y_pred)

1396.033534032397

In [ ]:
mean_absolute_percentage_error(y_test,y_pred)

1.017922214038592

In [ ]:
mean_absolute_error(y_test,y_pred)

26.893139267041093

In [ ]:
r2_score(y_test,y_pred)

0.9164258612676994

### HyperParameter Tunning : Grid Search

In [ ]:
from sklearn.model_selection import GridSearchCV
Parameters={'n_estimators':[10,20,30,100,500],'max_features':['auto','sqrt'],'min_samples_split':[4,8],'bootstrap':['True','False']}
gridsearch=GridSearchCV(RandomForestRegressor(),Parameters)
gridsearch.fit(x_train,y_train)

GridSearchCV(estimator=RandomForestRegressor(),
             param_grid={'bootstrap': ['True', 'False'],
                         'max_features': ['auto', 'sqrt'],
                         'min_samples_split': [4, 8],
                         'n_estimators': [10, 20, 30, 100, 500]})

In [ ]:
gridsearch.best_params_
{'bootstrap':True,'max_features':'auto','min_samples_split': 4,'n_estimators': 200}

{'bootstrap': True,
 'max_features': 'auto',
 'min_samples_split': 4,
 'n_estimators': 200}

In [ ]:
gridsearch.best_score_

0.8996908729376953

In [ ]:
gridsearch.best_estimator_

RandomForestRegressor(bootstrap='True', min_samples_split=4, n_estimators=500)

In [ ]:
gridsearch.best_index_

4

In [ ]:
y_pred_grid=gridsearch.predict(x_test)

In [ ]:
mean_absolute_error(y_test,y_pred_grid)

26.853686717749166

In [ ]:
r2_score(y_test,y_pred_grid)

0.9158557530549318

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
%%capture
!wget -nc https://raw.githubusercontent.com/brpy/colab-pdf/master/colab_pdf.py
from colab_pdf import colab_pdf

In [ ]:
colab_pdf('Random Forest Regression of Generated Data.ipynb')





[NbConvertApp] Converting notebook /content/drive/MyDrive/Colab Notebooks/Random Forest Regression of Generated Data.ipynb to pdf
[NbConvertApp] Writing 44949 bytes to ./notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', './notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', './notebook']
[NbConvertApp] WARNING | bibtex had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 47155 bytes to /content/drive/My Drive/Random Forest Regression of Generated Data.pdf


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

'File ready to be Downloaded and Saved to Drive'